### 课程查询接口 网关
POST http://{{gateway_host}}/content/course/list?pageNo=1&pageSize=5
Content-Type: application/json

{
  "auditStatus": "202004",
  "courseName": "java",
  "publishStatus": ""
}

### 课程查询接口
POST http://{{content_host}}/content/course/list?pageNo=1&pageSize=5
Content-Type: application/json

{
  "auditStatus": "202004",
  "courseName": "java",
  "publishStatus": ""
}

### 新增课程接口
POST http://{{content_host}}/content/course
Content-Type: application/json

{
  "mt": "1-1-1",
  "st": "1-1",
  "charge": "201001",
  "description": "string",
  "grade": "string",
  "name": "",
  "originalPrice": 0,
  "phone": "string",
  "pic": "0",
  "price": 10,
  "qq": "string",
  "tags": "",
  "teachmode": "200002",
  "users": "初级人员",
  "validDays": 0,
  "wechat": "string"
}

###
GET http://{{content_host}}/content/course-category/tree-nodes

# http://localhost:63040/content/swagger-ui.html
<> 2023-02-07T223955.404.html

### 课程查询 带JWT令牌
GET {{content_host}}/content/course/40
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ6aGFuZ3NhbiIsInNjb3BlIjpbImFsbCJdLCJleHAiOjE2ODY0MDI5MTMsImF1dGhvcml0aWVzIjpbInAxIl0sImp0aSI6IjdjNWY1YjY5LTRkODUtNDk4Zi1iZmU3LTE2OGU1ZjNmMzcxOSIsImNsaWVudF9pZCI6IlhjV2ViQXBwIn0.F_G_fWHy3nVGd5GPvFN-a_z6yg3qo18wovvj-qd7-UE

### 课程计划查询
GET {{content_host}}/content/teachplan/117/tree-nodes
Content-Type: application/json
