spring:
  application:
    name: content-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://139.198.181.54:3306/xc_content?serverTimezone=UTC&userUnicode=true&useSSL=false&
    username: root
    password: Dcp#7ujm
# 日志文件配置路径
logging:
  config: classpath:log4j2-dev.xml

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.xiaomi.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0